// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::circle_recombine_timer_type::CircleRecombineTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CircleRecombineArgs {
    pub timer: CircleRecombineTimer,
}

impl From<CircleRecombineArgs> for super::Reducer {
    fn from(args: CircleRecombineArgs) -> Self {
        Self::CircleRecombine { timer: args.timer }
    }
}

impl __sdk::InModule for CircleRecombineArgs {
    type Module = super::RemoteModule;
}

pub struct CircleRecombineCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `circle_recombine`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait circle_recombine {
    /// Request that the remote module invoke the reducer `circle_recombine` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_circle_recombine`] callbacks.
    fn circle_recombine(&self, timer: CircleRecombineTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `circle_recombine`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CircleRecombineCallbackId`] can be passed to [`Self::remove_on_circle_recombine`]
    /// to cancel the callback.
    fn on_circle_recombine(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &CircleRecombineTimer) + Send + 'static,
    ) -> CircleRecombineCallbackId;
    /// Cancel a callback previously registered by [`Self::on_circle_recombine`],
    /// causing it not to run in the future.
    fn remove_on_circle_recombine(&self, callback: CircleRecombineCallbackId);
}

impl circle_recombine for super::RemoteReducers {
    fn circle_recombine(&self, timer: CircleRecombineTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("circle_recombine", CircleRecombineArgs { timer })
    }
    fn on_circle_recombine(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &CircleRecombineTimer) + Send + 'static,
    ) -> CircleRecombineCallbackId {
        CircleRecombineCallbackId(self.imp.on_reducer(
            "circle_recombine",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CircleRecombine { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_circle_recombine(&self, callback: CircleRecombineCallbackId) {
        self.imp.remove_on_reducer("circle_recombine", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `circle_recombine`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_circle_recombine {
    /// Set the call-reducer flags for the reducer `circle_recombine` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn circle_recombine(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_circle_recombine for super::SetReducerFlags {
    fn circle_recombine(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("circle_recombine", flags);
    }
}
