// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::circle_recombine_timer_type::CircleRecombineTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `circle_recombine_timer`.
///
/// Obtain a handle from the [`CircleRecombineTimerTableAccess::circle_recombine_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.circle_recombine_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.circle_recombine_timer().on_insert(...)`.
pub struct CircleRecombineTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<CircleRecombineTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `circle_recombine_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CircleRecombineTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CircleRecombineTimerTableHandle`], which mediates access to the table `circle_recombine_timer`.
    fn circle_recombine_timer(&self) -> CircleRecombineTimerTableHandle<'_>;
}

impl CircleRecombineTimerTableAccess for super::RemoteTables {
    fn circle_recombine_timer(&self) -> CircleRecombineTimerTableHandle<'_> {
        CircleRecombineTimerTableHandle {
            imp: self
                .imp
                .get_table::<CircleRecombineTimer>("circle_recombine_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CircleRecombineTimerInsertCallbackId(__sdk::CallbackId);
pub struct CircleRecombineTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CircleRecombineTimerTableHandle<'ctx> {
    type Row = CircleRecombineTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CircleRecombineTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CircleRecombineTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CircleRecombineTimerInsertCallbackId {
        CircleRecombineTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CircleRecombineTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CircleRecombineTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CircleRecombineTimerDeleteCallbackId {
        CircleRecombineTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CircleRecombineTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CircleRecombineTimer>("circle_recombine_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct CircleRecombineTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CircleRecombineTimerTableHandle<'ctx> {
    type UpdateCallbackId = CircleRecombineTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CircleRecombineTimerUpdateCallbackId {
        CircleRecombineTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CircleRecombineTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CircleRecombineTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CircleRecombineTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `circle_recombine_timer`,
/// which allows point queries on the field of the same name
/// via the [`CircleRecombineTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.circle_recombine_timer().scheduled_id().find(...)`.
pub struct CircleRecombineTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CircleRecombineTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CircleRecombineTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `circle_recombine_timer`.
    pub fn scheduled_id(&self) -> CircleRecombineTimerScheduledIdUnique<'ctx> {
        CircleRecombineTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CircleRecombineTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CircleRecombineTimer> {
        self.imp.find(col_val)
    }
}
