// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConnectArgs {}

impl From<ConnectArgs> for super::Reducer {
    fn from(args: ConnectArgs) -> Self {
        Self::Connect
    }
}

impl __sdk::InModule for ConnectArgs {
    type Module = super::RemoteModule;
}

pub struct ConnectCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `connect`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait connect {
    /// Request that the remote module invoke the reducer `connect` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_connect`] callbacks.
    fn connect(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `connect`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ConnectCallbackId`] can be passed to [`Self::remove_on_connect`]
    /// to cancel the callback.
    fn on_connect(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ConnectCallbackId;
    /// Cancel a callback previously registered by [`Self::on_connect`],
    /// causing it not to run in the future.
    fn remove_on_connect(&self, callback: ConnectCallbackId);
}

impl connect for super::RemoteReducers {
    fn connect(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("connect", ConnectArgs {})
    }
    fn on_connect(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> ConnectCallbackId {
        ConnectCallbackId(self.imp.on_reducer(
            "connect",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Connect {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_connect(&self, callback: ConnectCallbackId) {
        self.imp.remove_on_reducer("connect", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `connect`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_connect {
    /// Set the call-reducer flags for the reducer `connect` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn connect(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_connect for super::SetReducerFlags {
    fn connect(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("connect", flags);
    }
}
