// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::consume_entity_timer_type::ConsumeEntityTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `consume_entity_timer`.
///
/// Obtain a handle from the [`ConsumeEntityTimerTableAccess::consume_entity_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.consume_entity_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consume_entity_timer().on_insert(...)`.
pub struct ConsumeEntityTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<ConsumeEntityTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `consume_entity_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConsumeEntityTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConsumeEntityTimerTableHandle`], which mediates access to the table `consume_entity_timer`.
    fn consume_entity_timer(&self) -> ConsumeEntityTimerTableHandle<'_>;
}

impl ConsumeEntityTimerTableAccess for super::RemoteTables {
    fn consume_entity_timer(&self) -> ConsumeEntityTimerTableHandle<'_> {
        ConsumeEntityTimerTableHandle {
            imp: self
                .imp
                .get_table::<ConsumeEntityTimer>("consume_entity_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConsumeEntityTimerInsertCallbackId(__sdk::CallbackId);
pub struct ConsumeEntityTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConsumeEntityTimerTableHandle<'ctx> {
    type Row = ConsumeEntityTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ConsumeEntityTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConsumeEntityTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsumeEntityTimerInsertCallbackId {
        ConsumeEntityTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ConsumeEntityTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConsumeEntityTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConsumeEntityTimerDeleteCallbackId {
        ConsumeEntityTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ConsumeEntityTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ConsumeEntityTimer>("consume_entity_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct ConsumeEntityTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ConsumeEntityTimerTableHandle<'ctx> {
    type UpdateCallbackId = ConsumeEntityTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ConsumeEntityTimerUpdateCallbackId {
        ConsumeEntityTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ConsumeEntityTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ConsumeEntityTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ConsumeEntityTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `consume_entity_timer`,
/// which allows point queries on the field of the same name
/// via the [`ConsumeEntityTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.consume_entity_timer().scheduled_id().find(...)`.
pub struct ConsumeEntityTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ConsumeEntityTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ConsumeEntityTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `consume_entity_timer`.
    pub fn scheduled_id(&self) -> ConsumeEntityTimerScheduledIdUnique<'ctx> {
        ConsumeEntityTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ConsumeEntityTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<ConsumeEntityTimer> {
        self.imp.find(col_val)
    }
}
