// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DisconnectArgs {}

impl From<DisconnectArgs> for super::Reducer {
    fn from(args: DisconnectArgs) -> Self {
        Self::Disconnect
    }
}

impl __sdk::InModule for DisconnectArgs {
    type Module = super::RemoteModule;
}

pub struct DisconnectCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `disconnect`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait disconnect {
    /// Request that the remote module invoke the reducer `disconnect` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_disconnect`] callbacks.
    fn disconnect(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `disconnect`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DisconnectCallbackId`] can be passed to [`Self::remove_on_disconnect`]
    /// to cancel the callback.
    fn on_disconnect(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> DisconnectCallbackId;
    /// Cancel a callback previously registered by [`Self::on_disconnect`],
    /// causing it not to run in the future.
    fn remove_on_disconnect(&self, callback: DisconnectCallbackId);
}

impl disconnect for super::RemoteReducers {
    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("disconnect", DisconnectArgs {})
    }
    fn on_disconnect(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> DisconnectCallbackId {
        DisconnectCallbackId(self.imp.on_reducer(
            "disconnect",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Disconnect {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_disconnect(&self, callback: DisconnectCallbackId) {
        self.imp.remove_on_reducer("disconnect", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `disconnect`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_disconnect {
    /// Set the call-reducer flags for the reducer `disconnect` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn disconnect(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_disconnect for super::SetReducerFlags {
    fn disconnect(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("disconnect", flags);
    }
}
