// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnterGameArgs {
    pub name: String,
}

impl From<EnterGameArgs> for super::Reducer {
    fn from(args: EnterGameArgs) -> Self {
        Self::EnterGame { name: args.name }
    }
}

impl __sdk::InModule for EnterGameArgs {
    type Module = super::RemoteModule;
}

pub struct EnterGameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `enter_game`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait enter_game {
    /// Request that the remote module invoke the reducer `enter_game` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_enter_game`] callbacks.
    fn enter_game(&self, name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `enter_game`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EnterGameCallbackId`] can be passed to [`Self::remove_on_enter_game`]
    /// to cancel the callback.
    fn on_enter_game(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> EnterGameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_enter_game`],
    /// causing it not to run in the future.
    fn remove_on_enter_game(&self, callback: EnterGameCallbackId);
}

impl enter_game for super::RemoteReducers {
    fn enter_game(&self, name: String) -> __sdk::Result<()> {
        self.imp.call_reducer("enter_game", EnterGameArgs { name })
    }
    fn on_enter_game(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> EnterGameCallbackId {
        EnterGameCallbackId(self.imp.on_reducer(
            "enter_game",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EnterGame { name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, name)
            }),
        ))
    }
    fn remove_on_enter_game(&self, callback: EnterGameCallbackId) {
        self.imp.remove_on_reducer("enter_game", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `enter_game`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_enter_game {
    /// Set the call-reducer flags for the reducer `enter_game` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn enter_game(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_enter_game for super::SetReducerFlags {
    fn enter_game(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("enter_game", flags);
    }
}
