// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::food_type::Food;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `food`.
///
/// Obtain a handle from the [`FoodTableAccess::food`] method on [`super::RemoteTables`],
/// like `ctx.db.food()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.food().on_insert(...)`.
pub struct FoodTableHandle<'ctx> {
    imp: __sdk::TableHandle<Food>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `food`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FoodTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FoodTableHandle`], which mediates access to the table `food`.
    fn food(&self) -> FoodTableHandle<'_>;
}

impl FoodTableAccess for super::RemoteTables {
    fn food(&self) -> FoodTableHandle<'_> {
        FoodTableHandle {
            imp: self.imp.get_table::<Food>("food"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FoodInsertCallbackId(__sdk::CallbackId);
pub struct FoodDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FoodTableHandle<'ctx> {
    type Row = Food;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Food> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FoodInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FoodInsertCallbackId {
        FoodInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FoodInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FoodDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FoodDeleteCallbackId {
        FoodDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FoodDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Food>("food");
    _table.add_unique_constraint::<u32>("entity_id", |row| &row.entity_id);
}
pub struct FoodUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FoodTableHandle<'ctx> {
    type UpdateCallbackId = FoodUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FoodUpdateCallbackId {
        FoodUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FoodUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Food>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Food>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `food`,
/// which allows point queries on the field of the same name
/// via the [`FoodEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.food().entity_id().find(...)`.
pub struct FoodEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Food, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FoodTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `food`.
    pub fn entity_id(&self) -> FoodEntityIdUnique<'ctx> {
        FoodEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FoodEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<Food> {
        self.imp.find(col_val)
    }
}
