// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::move_all_players_timer_type::MoveAllPlayersTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `move_all_players_timer`.
///
/// Obtain a handle from the [`MoveAllPlayersTimerTableAccess::move_all_players_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.move_all_players_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.move_all_players_timer().on_insert(...)`.
pub struct MoveAllPlayersTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<MoveAllPlayersTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `move_all_players_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MoveAllPlayersTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MoveAllPlayersTimerTableHandle`], which mediates access to the table `move_all_players_timer`.
    fn move_all_players_timer(&self) -> MoveAllPlayersTimerTableHandle<'_>;
}

impl MoveAllPlayersTimerTableAccess for super::RemoteTables {
    fn move_all_players_timer(&self) -> MoveAllPlayersTimerTableHandle<'_> {
        MoveAllPlayersTimerTableHandle {
            imp: self
                .imp
                .get_table::<MoveAllPlayersTimer>("move_all_players_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MoveAllPlayersTimerInsertCallbackId(__sdk::CallbackId);
pub struct MoveAllPlayersTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MoveAllPlayersTimerTableHandle<'ctx> {
    type Row = MoveAllPlayersTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MoveAllPlayersTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MoveAllPlayersTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MoveAllPlayersTimerInsertCallbackId {
        MoveAllPlayersTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MoveAllPlayersTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MoveAllPlayersTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MoveAllPlayersTimerDeleteCallbackId {
        MoveAllPlayersTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MoveAllPlayersTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MoveAllPlayersTimer>("move_all_players_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct MoveAllPlayersTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MoveAllPlayersTimerTableHandle<'ctx> {
    type UpdateCallbackId = MoveAllPlayersTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MoveAllPlayersTimerUpdateCallbackId {
        MoveAllPlayersTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MoveAllPlayersTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MoveAllPlayersTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MoveAllPlayersTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `move_all_players_timer`,
/// which allows point queries on the field of the same name
/// via the [`MoveAllPlayersTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.move_all_players_timer().scheduled_id().find(...)`.
pub struct MoveAllPlayersTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MoveAllPlayersTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MoveAllPlayersTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `move_all_players_timer`.
    pub fn scheduled_id(&self) -> MoveAllPlayersTimerScheduledIdUnique<'ctx> {
        MoveAllPlayersTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MoveAllPlayersTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MoveAllPlayersTimer> {
        self.imp.find(col_val)
    }
}
