// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::move_all_players_timer_type::MoveAllPlayersTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MoveAllPlayersArgs {
    pub timer: MoveAllPlayersTimer,
}

impl From<MoveAllPlayersArgs> for super::Reducer {
    fn from(args: MoveAllPlayersArgs) -> Self {
        Self::MoveAllPlayers { timer: args.timer }
    }
}

impl __sdk::InModule for MoveAllPlayersArgs {
    type Module = super::RemoteModule;
}

pub struct MoveAllPlayersCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `move_all_players`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait move_all_players {
    /// Request that the remote module invoke the reducer `move_all_players` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_move_all_players`] callbacks.
    fn move_all_players(&self, timer: MoveAllPlayersTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `move_all_players`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MoveAllPlayersCallbackId`] can be passed to [`Self::remove_on_move_all_players`]
    /// to cancel the callback.
    fn on_move_all_players(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &MoveAllPlayersTimer) + Send + 'static,
    ) -> MoveAllPlayersCallbackId;
    /// Cancel a callback previously registered by [`Self::on_move_all_players`],
    /// causing it not to run in the future.
    fn remove_on_move_all_players(&self, callback: MoveAllPlayersCallbackId);
}

impl move_all_players for super::RemoteReducers {
    fn move_all_players(&self, timer: MoveAllPlayersTimer) -> __sdk::Result<()> {
        self.imp
            .call_reducer("move_all_players", MoveAllPlayersArgs { timer })
    }
    fn on_move_all_players(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &MoveAllPlayersTimer) + Send + 'static,
    ) -> MoveAllPlayersCallbackId {
        MoveAllPlayersCallbackId(self.imp.on_reducer(
            "move_all_players",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MoveAllPlayers { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_move_all_players(&self, callback: MoveAllPlayersCallbackId) {
        self.imp.remove_on_reducer("move_all_players", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `move_all_players`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_move_all_players {
    /// Set the call-reducer flags for the reducer `move_all_players` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn move_all_players(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_move_all_players for super::SetReducerFlags {
    fn move_all_players(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("move_all_players", flags);
    }
}
