// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::spawn_food_timer_type::SpawnFoodTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SpawnFoodArgs {
    pub timer: SpawnFoodTimer,
}

impl From<SpawnFoodArgs> for super::Reducer {
    fn from(args: SpawnFoodArgs) -> Self {
        Self::SpawnFood { timer: args.timer }
    }
}

impl __sdk::InModule for SpawnFoodArgs {
    type Module = super::RemoteModule;
}

pub struct SpawnFoodCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `spawn_food`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait spawn_food {
    /// Request that the remote module invoke the reducer `spawn_food` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_spawn_food`] callbacks.
    fn spawn_food(&self, timer: SpawnFoodTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `spawn_food`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SpawnFoodCallbackId`] can be passed to [`Self::remove_on_spawn_food`]
    /// to cancel the callback.
    fn on_spawn_food(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &SpawnFoodTimer) + Send + 'static,
    ) -> SpawnFoodCallbackId;
    /// Cancel a callback previously registered by [`Self::on_spawn_food`],
    /// causing it not to run in the future.
    fn remove_on_spawn_food(&self, callback: SpawnFoodCallbackId);
}

impl spawn_food for super::RemoteReducers {
    fn spawn_food(&self, timer: SpawnFoodTimer) -> __sdk::Result<()> {
        self.imp.call_reducer("spawn_food", SpawnFoodArgs { timer })
    }
    fn on_spawn_food(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &SpawnFoodTimer) + Send + 'static,
    ) -> SpawnFoodCallbackId {
        SpawnFoodCallbackId(self.imp.on_reducer(
            "spawn_food",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SpawnFood { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_spawn_food(&self, callback: SpawnFoodCallbackId) {
        self.imp.remove_on_reducer("spawn_food", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `spawn_food`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_spawn_food {
    /// Set the call-reducer flags for the reducer `spawn_food` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn spawn_food(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_spawn_food for super::SetReducerFlags {
    fn spawn_food(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("spawn_food", flags);
    }
}
