// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::spawn_food_timer_type::SpawnFoodTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `spawn_food_timer`.
///
/// Obtain a handle from the [`SpawnFoodTimerTableAccess::spawn_food_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.spawn_food_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.spawn_food_timer().on_insert(...)`.
pub struct SpawnFoodTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<SpawnFoodTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `spawn_food_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SpawnFoodTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SpawnFoodTimerTableHandle`], which mediates access to the table `spawn_food_timer`.
    fn spawn_food_timer(&self) -> SpawnFoodTimerTableHandle<'_>;
}

impl SpawnFoodTimerTableAccess for super::RemoteTables {
    fn spawn_food_timer(&self) -> SpawnFoodTimerTableHandle<'_> {
        SpawnFoodTimerTableHandle {
            imp: self.imp.get_table::<SpawnFoodTimer>("spawn_food_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SpawnFoodTimerInsertCallbackId(__sdk::CallbackId);
pub struct SpawnFoodTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SpawnFoodTimerTableHandle<'ctx> {
    type Row = SpawnFoodTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SpawnFoodTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SpawnFoodTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpawnFoodTimerInsertCallbackId {
        SpawnFoodTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SpawnFoodTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SpawnFoodTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SpawnFoodTimerDeleteCallbackId {
        SpawnFoodTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SpawnFoodTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SpawnFoodTimer>("spawn_food_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct SpawnFoodTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SpawnFoodTimerTableHandle<'ctx> {
    type UpdateCallbackId = SpawnFoodTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SpawnFoodTimerUpdateCallbackId {
        SpawnFoodTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SpawnFoodTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<SpawnFoodTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SpawnFoodTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `spawn_food_timer`,
/// which allows point queries on the field of the same name
/// via the [`SpawnFoodTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.spawn_food_timer().scheduled_id().find(...)`.
pub struct SpawnFoodTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SpawnFoodTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SpawnFoodTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `spawn_food_timer`.
    pub fn scheduled_id(&self) -> SpawnFoodTimerScheduledIdUnique<'ctx> {
        SpawnFoodTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SpawnFoodTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SpawnFoodTimer> {
        self.imp.find(col_val)
    }
}
