// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SuicideArgs {}

impl From<SuicideArgs> for super::Reducer {
    fn from(args: SuicideArgs) -> Self {
        Self::Suicide
    }
}

impl __sdk::InModule for SuicideArgs {
    type Module = super::RemoteModule;
}

pub struct SuicideCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `suicide`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait suicide {
    /// Request that the remote module invoke the reducer `suicide` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_suicide`] callbacks.
    fn suicide(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `suicide`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SuicideCallbackId`] can be passed to [`Self::remove_on_suicide`]
    /// to cancel the callback.
    fn on_suicide(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> SuicideCallbackId;
    /// Cancel a callback previously registered by [`Self::on_suicide`],
    /// causing it not to run in the future.
    fn remove_on_suicide(&self, callback: SuicideCallbackId);
}

impl suicide for super::RemoteReducers {
    fn suicide(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("suicide", SuicideArgs {})
    }
    fn on_suicide(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> SuicideCallbackId {
        SuicideCallbackId(self.imp.on_reducer(
            "suicide",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::Suicide {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_suicide(&self, callback: SuicideCallbackId) {
        self.imp.remove_on_reducer("suicide", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `suicide`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_suicide {
    /// Set the call-reducer flags for the reducer `suicide` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn suicide(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_suicide for super::SetReducerFlags {
    fn suicide(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("suicide", flags);
    }
}
